# Default values for supabase
nameOverride: ""
fullnameOverride: ""

# Global settings
global:
  version: "1.25.02"  # Supabase version
  postgresql:
    auth:
      postgresPassword: "postgres"  # Change this in production!
      database: "postgres"

# PostgreSQL settings
postgresql:
  enabled: true
  primary:
    persistence:
      size: 10Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Supabase API settings
api:
  image:
    repository: supabase/rest
    tag: "1.25.02"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 54321

# Supabase Studio settings
studio:
  image:
    repository: supabase/studio
    tag: "1.25.02"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 3000

# Ingress configuration
ingress:
  enabled: true  # Set to true to enable ingress
  className: nginx  # Your ingress class name
  annotations:
    cert-manager.io/cluster-issuer: your-actual-issuer-name
    kubernetes.io/ingress.class: nginx
    # For SSL/TLS
    # kubernetes.io/tls-acme: "true"
    # For specific ingress controller settings
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: your-actual-domain.com  # Replace with your actual domain
      paths:
        - path: /
          pathType: Prefix
  tls:  # Enable TLS by adding your secret
    - secretName: your-actual-tls-secret-name
      hosts:
        - your-actual-domain.com 