# Default values for supabase
nameOverride: ""
fullnameOverride: ""

# Global settings
global:
  version: "1.25.02"  # Supabase version
  postgresql:
    auth:
      database: postgres
      username: postgres
      password: postgres
      secretName: supabase-db-credentials

# Secret configuration
secret:
  jwt:
    anonKey: "your-anon-key"  # Change in production!
    serviceKey: "your-service-role-key"  # Change in production!
    secret: "your-super-secret-jwt-token-with-at-least-32-characters-long"  # Change in production!
  db:
    username: "postgres"
    password: "postgres"  # Change in production!
    database: "postgres"

# Database settings
db:
  enabled: true
  image:
    repository: supabase/postgres
    tag: "15.1.0.117"
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  service:
    type: ClusterIP
    port: 5432

# Studio settings
studio:
  enabled: true
  image:
    repository: supabase/studio
    tag: "20240205-0b7a0c1"
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: supabase.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Auth settings
auth:
  enabled: true
  image:
    repository: supabase/gotrue
    tag: "v2.132.3"
  service:
    type: ClusterIP
    port: 9999
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# REST API settings
rest:
  enabled: true
  image:
    repository: postgrest/postgrest
    tag: "v11.2.0"
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Realtime settings
realtime:
  enabled: true
  image:
    repository: supabase/realtime
    tag: "v2.25.50"
  service:
    type: ClusterIP
    port: 4000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Kong Gateway settings
kong:
  enabled: true
  image:
    repository: kong
    tag: "2.8.1"
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Analytics settings
analytics:
  enabled: true
  image:
    repository: supabase/logflare
    tag: "1.12.0"
  service:
    type: ClusterIP
    port: 4000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Functions settings
functions:
  enabled: true
  image:
    repository: supabase/edge-runtime
    tag: "v1.67.4"
  service:
    type: ClusterIP
    port: 54321
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: your-actual-issuer-name
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: your-actual-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: your-actual-tls-secret-name
      hosts:
        - your-actual-domain.com 