# Default values for supabase
nameOverride: ""
fullnameOverride: ""

# Global settings
global:
  postgresql:
    auth:
      postgresPassword: "postgres"  # Change this in production!
      database: "postgres"

# PostgreSQL settings
postgresql:
  enabled: true
  primary:
    persistence:
      size: 10Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Supabase API settings
api:
  image:
    repository: supabase/edge-runtime
    tag: "latest"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 54321

# Supabase Studio settings
studio:
  image:
    repository: supabase/studio
    tag: "latest"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 3000

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [] 