apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supabase.fullname" . }}-db
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }} 