{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.fullname" . }}-db
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "supabase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
{{- end }} 