{{- if and .Values.studio.enabled .Values.studio.ingress.enabled }}
{{- $fullName := include "supabase.fullname" . -}}
{{- $svcPort := .Values.studio.service.port -}}
{{- if and .Values.studio.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.studio.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.studio.ingress.annotations "kubernetes.io/ingress.class" .Values.studio.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-studio
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: studio
  {{- with .Values.studio.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.studio.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.studio.ingress.className }}
  {{- end }}
  {{- if .Values.studio.ingress.tls }}
  tls:
    {{- range .Values.studio.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.studio.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}-studio
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }} 