apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.fullname" . }}-analytics
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: analytics
  template:
    metadata:
      labels:
        {{- include "supabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: analytics
    spec:
      containers:
        - name: analytics
          image: "{{ .Values.analytics.image.repository }}:{{ .Values.analytics.image.tag }}"
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          env:
            - name: LOGFLARE_NODE_HOST
              value: "127.0.0.1"
            - name: DB_USERNAME
              value: "supabase_admin"
            - name: DB_DATABASE
              value: "_supabase"
            - name: DB_HOSTNAME
              value: "{{ include "supabase.fullname" . }}-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_PASSWORD
              value: {{ .Values.global.postgresql.auth.postgresPassword }}
            - name: DB_SCHEMA
              value: "_analytics"
            - name: LOGFLARE_API_KEY
              value: "your-logflare-api-key"
            - name: LOGFLARE_SINGLE_TENANT
              value: "true"
            - name: LOGFLARE_SUPABASE_MODE
              value: "true"
            - name: LOGFLARE_MIN_CLUSTER_SIZE
              value: "1"
            - name: POSTGRES_BACKEND_URL
              value: "postgresql://supabase_admin:{{ .Values.global.postgresql.auth.postgresPassword }}@{{ include "supabase.fullname" . }}-postgresql:5432/_supabase"
            - name: POSTGRES_BACKEND_SCHEMA
              value: "_analytics"
            - name: LOGFLARE_FEATURE_FLAG_OVERRIDE
              value: "multibackend=true"
          resources:
            {{- toYaml .Values.analytics.resources | nindent 12 }} 