apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.fullname" . }}-studio
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: studio
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: studio
  template:
    metadata:
      labels:
        {{- include "supabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: studio
    spec:
      containers:
        - name: studio
          image: "{{ .Values.studio.image.repository }}:{{ .Values.studio.image.tag }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: STUDIO_PG_META_URL
              value: "http://{{ include "supabase.fullname" . }}-meta:8080"
            - name: POSTGRES_PASSWORD
              value: {{ .Values.global.postgresql.auth.postgresPassword }}
            - name: DEFAULT_ORGANIZATION_NAME
              value: "Default Organization"
            - name: DEFAULT_PROJECT_NAME
              value: "Default Project"
            - name: SUPABASE_URL
              value: "http://{{ include "supabase.fullname" . }}-kong:8000"
            - name: SUPABASE_ANON_KEY
              value: "your-anon-key"
            - name: SUPABASE_SERVICE_KEY
              value: "your-service-role-key"
            - name: AUTH_JWT_SECRET
              value: "your-super-secret-jwt-token-with-at-least-32-characters-long"
          resources:
            {{- toYaml .Values.studio.resources | nindent 12 }} 